### ISSUE TITLE
Can not compile with Rust 1.0.0-beta5

### ISSUE THREAD

**Issue by alkan** [gchp/iota#104]
tmpfile dependency fails while compiling with the followin error:

/home/ayhan/.cargo/registry/src/github.com-1ecc6299db9ec823/tempfile-0.2.0/src/lib.rs:1:1: 1:34 error: unstable feature
/home/ayhan/.cargo/registry/src/github.com-1ecc6299db9ec823/tempfile-0.2.0/src/lib.rs:1 #![feature(convert, from_raw_os)]
                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error

**Comment by gchp** [comment]
Yeah, I'm not sure how to get around this really. There's a few dependencies which don't compile on beta, tempfile being one of them. I'd like to make Iota work with the beta release, but I'm not sure if its going to be possible. Unfortunately for now we are restricted to the nightly channel.

**Comment by gchp** [comment]
I'll leave this issue open though, because its something I'd like to investigate a bit more. Hopefully others might have some suggestions too!

**Comment by vinipsmaker** [comment]
I can compile with Rust 1.0.0. Issue closed?

**Comment by gchp** [comment]
Long since resolved :)
