### ISSUE TITLE
Move to start of line not working properly

### ISSUE THREAD

**Issue by jncraton** [gchp/iota#137]
Using Ctrl-a in emacs mode moves the cursor to the start of the second line in the file for me rather than the start of the current line. Ctrl-e works as expected and moves the cursor to the end of the line.

**Comment by gchp** [comment]
It appears that the cursor actually goes to the correct location, but the display is off. You can validate this by pressing ctrl-a, then typing something. The characters you type will appear on the correct line, not on the line the cursor is displayed.

**Comment by jncraton** [comment]
That's what I see as well. It's worth noting that the cursor position shown in the status bar is also the incorrect one until you insert a character or move the cursor.
