### ISSUE TITLE
Come up with a standardized interface for user interaction

### ISSUE THREAD

**Issue by pythonesque** [gchp/iota#64]
Thinking about things like saving a file, displaying errors, etc., we should have a standard interface for communicating with the user.  Things to think about:

* loading / saving a file
* displaying an error (short or long form)
* yes/no prompt
* selecting a buffer

@gchp mentioned that vigo has the concept of an Overlay.  We should look into that.

**Comment by gchp** [comment]
Created a PR for this. It needs some more work still, and can probably be generalised a bit more to make it more re-usable, but its functional. Check it out and see what you think
