### ISSUE TITLE
iota logo/icon

### ISSUE THREAD

**Issue by torwart** [gchp/iota#72]
I was bored and I have created a little bit using Photoshop. Its not finished but I think its ok ;)
If you want any changes, tell me.

![logo kopie](https://cloud.githubusercontent.com/assets/10358036/5587909/e10c1a8c-90f9-11e4-9964-36fe2dc76c23.png)

**Comment by gchp** [comment]
I just realised I never replied to this, my apologies!

This is awesome, thanks for taking the time to put it together! I hadn't really thought about a logo for the project just yet, and my photoshop skills are somewhat non-existant ;) so its cool to have this to go with, thanks!

**Comment by torwart** [comment]
@gchp
Its not a Problem to edit and work on something in blender. I have some ideas, and I think gray or an shiny orange would be great. Thats why I closed it for now, because first I changed my machine and second that I have some more ideas todo. I will reopen this up at a later point.
