### ISSUE TITLE
Relicense project under GPL

### ISSUE THREAD

**Issue by gchp** [gchp/iota#77]
I'd like to relicense the project under the GPL.

Obviously, this would mean that code contributed already to this project under the MIT license would need to be relicensed. In order to do this I would like the contributors of said code permission to have their contributions relicensed.

If you've contributed code to Iota up to this point, can you comment below and let me know if you are happy for your contributions to be relicensed under the GPL. Alternatively, if you're not happy for this, please also comment below or email me (email address in commit log).

Thanks!

**Comment by dlaronson** [comment]
I strongly support!

Sent from my android device.

-----Original Message-----

**Comment by Crespyl** [comment]
Certainly fine by me!

**Comment by pythonesque** [comment]
Fine by me.

**Comment by gchp** [comment]
@P1start @Arcterus @emctoo @pwoolcoc @reem @sschepens let me know what you think of this, thanks!

**Comment by sschepens** [comment]
Im in, go ahead!

**Comment by pwoolcoc** [comment]
Not a huge fan of the GPL, but it is your project, and I don't mind having my contribution re-licensed, so it is fine with me.

**Comment by reem** [comment]
Honestly I'd rather not, I strongly prefer licenses with less destructive capacity. Perhaps a license that mandates upstreaming but allows use?


At the end of the day though this is your project, so you are free to do what you want (I don't feel my contributions have been enough to warrant saying no) but I think you will receive less contribution from license-aware developers, as the GPL is not very popular.




I'm curious to hear your reasons for wanting to relicense. 


Thanks,
         Jonathan Reem

**Comment by emctoo** [comment]
Fine, go ahead!

**Comment by gchp** [comment]
In light of comments from @pwoolcoc and @reem I'm going to put this on hold for now. I had not considered that using the GPL may make the project less popular. Thinking about this, and the goals of Iota, mainly the extensibility & open source parts, it may be better in the long run to keep the MIT license which is much more permissive. Using MIT means that the project is free software, which I'm happy with. I also had a look around at other Rust project in the ecosystem, and it seems that MIT is the most popular license in the community, so it makes more sense to keep it here too. Perhaps will revisit this in the future, but closing as is for now. Thanks for the feedback nonetheless!
