### ISSUE TITLE
SIGILL on latest OSX

### ISSUE THREAD

**Issue by ruipacheco** [gchp/iota#80]
`git pull`
`cargo build --release`
`./target/release/iota`

and then

`fish: Job 1, './target/release/iota ' terminated by signal SIGILL (Illegal instruction)`

(I'm using the fish shell)

**Comment by pythonesque** [comment]
Does it happen with any other terminals?

**Comment by ruipacheco** [comment]
Latest zsh: 

[1]    49828 illegal hardware instruction  ./target/release/iota

**Comment by pythonesque** [comment]
Hm, and this happens immediately?

**Comment by ruipacheco** [comment]
Yep. As soon as I try to run the binary.

**Comment by pythonesque** [comment]
Hey, I get the same thing!  Someone must have screwed up :P  I'll see if I can figure out what went wrong, as it obviously was not doing this before.

**Comment by ruipacheco** [comment]
Maybe one of the dependencies.

Thanks!

**Comment by dlaronson** [comment]
Its probably a problem in gapbuffer's indexing introduced with the new changes to slicing. @gchp and I discussed it yesterday 

Sent from my android device.

-----Original Message-----

**Comment by gchp** [comment]
Sorry for late response. As @dlaronson said, this is something to do with the `GapBuffer` repo, investigating this at the moment!

**Comment by tomjakubowski** [comment]
Happens on `Linux elbridge 3.17.6-1-ARCH #1 SMP PREEMPT Sun Dec 7 23:43:32 UTC 2014 x86_64 GNU/Linux` too, with and without `--release`.

**Comment by gchp** [comment]
Submitted a PR which once merged will fix the issue.

https://github.com/dlaronson/gapbuffer/pull/7

**Comment by ruipacheco** [comment]
git pull-ed today and the issue was fixed.
