### ISSUE TITLE
updating the screenshot

### ISSUE THREAD

**Issue by torwart** [gchp/iota#84]
Like ``iota``, but screenshot looks old (because in header there is ``rdit``). Would be nice if you could update this.

**Comment by gchp** [comment]
Yeah, that screenshot was from ages ago!

**Comment by gchp** [comment]
Updated there, its not as pretty as the other screenshot, but I'm not on my mac at the moment to use its fancy screenshot effects :wink: 
Will update again later if I can!

**Comment by torwart** [comment]
But looks also very good. Like it and no problem :)
