### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by yeahnoob** [gchp/iota#93]
After `$cargo build`, run & get this error.
How deal with it?
```
$ ./target/iota
Illegal instruction (core dumped)
```
PS. 
Ubuntu 14.04 LTS x64;
Nightly Build's rustc and cargo.

**Comment by utkarshkukreti** [comment]
Same here on OSX 10.9.5.

    $ target/iota
    [1]    97292 illegal hardware instruction  target/iota

**Comment by gchp** [comment]
Yeah, same for me. Investigating now

**Comment by gchp** [comment]
Seems to be coming from this https://github.com/gchp/iota/blob/master/src/main.rs#L53-L56

I wonder if this has to do with some changes in http://github.com/nsf/termbox that landed yesterday. Rustbox relies on this, so it could be that some of those changes have messed things up for us.

**Comment by utkarshkukreti** [comment]
2 fields were [added `tb_event` struct](https://github.com/nsf/termbox/commit/4fad64dc07a732b28d30e48e22742ca62be2035d#diff-c88f445a97b15816de521c5d1a4f7e10R153).. maybe that?

**Comment by suhr** [comment]
[Calling `tb_select_input_mode` before `tb_init`](https://github.com/gchp/rustbox/blob/master/src/rustbox.rs#L365). `tb_select_input_mode` calls `bytebuffer_puts` and `bytebuffer_flush`, but buffers are not initialized before `tb_init` is called.

PS: use rust-gdb, it rocks.

**Comment by pythonesque** [comment]
Heh, I had actually pointed this out earlier after your commit, but at the time it wasn't causing any issues so it wasn't urgent.

**Comment by crespyl** [comment]
I was having trouble replicating the problem until I updated the rustc nightly.  It was only ~1 day old, but with the compiler update I now get the illegal instruction.  It looks like this is one of those cases where it probably should never have worked in the first place.

**Comment by gchp** [comment]
Yup, @suhr and @pythonesque were right!

I've update released rustbox `0.2.14` which fixed this. Should be good to go!
